### ISSUE TITLE
Paper PDF

### ISSUE THREAD

**Issue by yizhiwang96** [thuliu-yt16/dualvector#2]
Hi, Yingtian, congrats to your new work accepted by CVPR. Where can I find the paper? Are you going to upload it to Arxiv?

**Comment by thuliu-yt16** [comment]
Thank you! I haven't uploaded it to Arxiv but I will. The arxiv link will be updated to README once ready.

**Comment by thuliu-yt16** [comment]
Hi, Yizhi, the paper is now available at OpenAccess[[pdf](https://openaccess.thecvf.com/content/CVPR2023/papers/Liu_DualVector_Unsupervised_Vector_Font_Synthesis_With_Dual-Part_Representation_CVPR_2023_paper.pdf)][[supp](https://openaccess.thecvf.com/content/CVPR2023/supplemental/Liu_DualVector_Unsupervised_Vector_CVPR_2023_supplemental.zip)] and Arxiv[[pdf](https://arxiv.org/abs/2305.10462)].

**Comment by yizhiwang96** [comment]
Thx!
