### ISSUE TITLE
Some dependencies are unclear. What should forceZ do?

### ISSUE THREAD

**Issue by rmast** [thuliu-yt16/dualvector#3]
I can't find any fork of https://github.com/mathandy/svgpathtools that supports forceZ as keyword argument for wsvg.

Where can I find the right fork of svgpathtools for this forceZ?
```
(dualvector9) rmast@Ubuntu22colab:~/dualvector$ python eval/post_refinement.py --outdir eval/save/test_recon/refined --input eval/save/test_recon/rec_init2/ --fmin 0 --fmax 0
  0%|                                                                                       | 0/52 [00:00<?, ?it/s]eval/save/test_recon/rec_init2/0000/00_init.svg
  0%|                                                                                       | 0/52 [00:18<?, ?it/s]
Traceback (most recent call last):
  File "/home/rmast/dualvector/eval/post_refinement.py", line 182, in <module>
    main()
  File "/home/rmast/dualvector/eval/post_refinement.py", line 175, in main
    loss_render = post_refinement(path, font, glyph)
  File "/home/rmast/dualvector/eval/post_refinement.py", line 98, in post_refinement
    success = svg_file_simplification(dst_svg_path.replace('.svg', f'_{i-1}.svg'), dst_svg_path.replace('.svg', f'_{i-1}_sim.svg'),\
  File "/home/rmast/dualvector/eval/svg_simplification.py", line 255, in svg_file_simplification
    wsvg(paths=[new_path], attributes=attributes, svg_attributes=svg_attributes, forceZ=True, filename=dst_path)
TypeError: wsvg() got an unexpected keyword argument 'forceZ'

```

**Comment by thuliu-yt16** [comment]
Sorry, I miss the modification. We added the forceZ option to force inserting a 'z' command after each path to ensure a closed path. 

I will update the modified code and you can try it again. We use svgpathtools 1.4.4.

**Comment by thuliu-yt16** [comment]
see here: [svgpathtools_modified](https://github.com/thuliu-yt16/dualvector/tree/main/eval/svgpathtools_modified)

**Comment by Adi2334** [comment]
I downloaded the updated files and replaced with old files in svgpathtools, but still I am getting the same error.

**Comment by thuliu-yt16** [comment]
I guess you need to replace the corresponding files in svgpathtools installed in your environment.

**Comment by thuliu-yt16** [comment]
> I downloaded the updated files and replaced with old files in svgpathtools, but still I am getting the same error.

Can you paste the error here? If you update the files correctly, I think at least, the wsvg function has the argument forceZ.
